# Bienvenidos

Esto es un notebook. Podemos escribir en lenguaje Markdown, el cual nos permite:
* Listas
* Escribir en **negrita** y *cursiva*
* Más información aquí: [Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

![](https://media.giphy.com/media/l0MYC0LajbaPoEADu/giphy.gif )

### PREGUNTAD!!

Sobretodo si os perdeis, no lleguemos a casos donde no sepais que estamos haciendo.

![Imagen no cargada. Edita y borra la @ ](https://img.buzzfeed.com/buzzfeed-static/static/2014-10/26/6/enhanced/webdr08/longform-original-14836-1414320930-10.jpg @ )

# Introducción

![ ](diagrama_resumen.png )

# Bibliografía 

Sobre **estadística**: [Practical Statistics for Data Scientists: 50 Essential Concepts](https://www.amazon.com/Practical-Statistics-Data-Scientists-Essential/dp/1491952962/ref=sr_1_3?ie=UTF8&qid=1518719786)


Sobre **R**: [R for Data Science: Import, Tidy, Transform, Visualize, and Model Data](https://www.amazon.com/Data-Science-Transform-Visualize-Model/dp/1491910399/ref=sr_1_1?ie=UTF8&qid=1518791084) Este libro es bastante completo, abarca mucho temario que no veremos por falta de tiempo.
                    


# Introducción a R

R es un lenguaje de programación orientado a la estadística.

Algo parecido a SPSS o Matlab.

Es código abierto y se entrega bajo licencia GPL (versión 2 o posterior). Además existen multitud de paquetes que complementan su funcionalidad.

## Asignaciones

Podemos usar <- o el símbolo = para asignar un valor a una variable

In [1]:
a <- 9
print(a)

b = 2
b

[1] 9


[1] 2

## Operaciones

In [2]:
a+b #Suma

a^b #potencia

a %% b #módulo

[1] 11

[1] 81

[1] 1

## Funciones básicas

Las funciones 
 * siempre acaban en ()
 * pueden recibir un número variable de parámetros
 * pueden existir parámetros por defecto

Ver las variables en memoria:

In [3]:
ls()

[1] "a" "b"

Ver el tipo de variable:

In [4]:
typeof(a)

[1] "double"

# Tipos de datos

## double

In [5]:
a<-2018
a
typeof(a)

[1] 2018

[1] "double"

In [6]:
b<-exp(1)
b
typeof(b)

[1] 2.718282

[1] "double"

## integer

In [7]:
ai<-as.integer(3.789)
ai
typeof(ai)

[1] 3

[1] "integer"

## Diferencias entre  integer y double

El número más grande que podemos representar es diferente:

In [8]:
.Machine$integer.max
.Machine$double.xmax

[1] 2147483647

[1] 1.797693e+308

El tamaño que ocupan en memoria es:

In [9]:
object.size(ai)
object.size(b)

48 bytes

48 bytes

## character

In [10]:
s1 <- " Discovery"
s1
typeof(s1)

[1] " Discovery"

[1] "character"

Las cadenas de texto se pueden concatenar usando el comando paste

In [11]:
paste(s1,"Lorca","Tardígrado", sep = "-||-")

[1] " Discovery-||-Lorca-||-Tardígrado"

## Logical

In [12]:
b1 <- TRUE
b2 <- T
b3 <- FALSE
print(paste("El valor de b1 es",b1))
print(paste("El valor de b2 es",b2))
print(paste("El valor de b3 es",b3))

[1] "El valor de b1 es TRUE"
[1] "El valor de b2 es TRUE"
[1] "El valor de b3 es FALSE"


In [13]:
print(paste("b1 AND b3:",b1 & b3))
print(paste("b1 OR  b3:",b1 | b3))
print(paste("b1 XOR b3:",xor(b1 ,b3)))
print(paste("   NOT b1:",!b1))

[1] "b1 AND b3: FALSE"
[1] "b1 OR  b3: TRUE"
[1] "b1 XOR b3: TRUE"
[1] "   NOT b1: FALSE"


## Vectores

Los vectores se crean con la función c(), todos los elementos de un vector son del mimo tipo. Es decir, no se podrían mezclar caracteres y double.

In [14]:
alturas<-c(1.80,1.60,1.50,1.90,1.75,1.63,1.65)
print(paste("alturas es una variable de tipo:",typeof(alturas)))
print("Podemos ver la estructura de un objeto con el comando str():")
str(alturas)

[1] "alturas es una variable de tipo: double"
[1] "Podemos ver la estructura de un objeto con el comando str():"
 num [1:7] 1.8 1.6 1.5 1.9 1.75 1.63 1.65


In [15]:
otroVector <- c("uno",2.0,"tres","14.0")
otroVector
str(otroVector)

[1] "uno"  "2"    "tres" "14.0"

 chr [1:4] "uno" "2" "tres" "14.0"


### Acceso a elementos

In [16]:
print(paste("El valor del tercer elemento es:",alturas[3]))

[1] "El valor del tercer elemento es: 1.5"


**¡¡En R los arrays empiezan en 1!!**
![Imagen no cargada. Edita y borra la @ ](https://i.redd.it/iwnqgrrbls5z.png @)

Podemos dar nombres a cada elemento

In [17]:
myVector <- c(nombre="Philip",apellido="García",teléfono=600100100)

In [18]:
myVector["nombre"]
myVector[2]
myVector["teléfono"]

nombre 
"Philip"

apellido 
"García"

teléfono 
"600100100"

In [19]:
#Los nombres de una variable se pueden ver con la función names()
names(myVector)

[1] "nombre"   "apellido" "teléfono"

### Operaciones con vectores

Al operar contra una variable se aplica esa operación a todos los elementos del vector

In [20]:
metro2pie<-3.28084
alturasEnPies<-alturas*metro2pie
alturasEnPies

[1] 5.905512 5.249344 4.921260 6.233596 5.741470 5.347769 5.413386

Si se opera con dos vectores de la misma longitud se aplica elemento a elemento.

In [21]:
alturaDeLosZapatos<-c(2,0,1,3,5,7,0)/100
alturaReal<-alturas-alturaDeLosZapatos
alturaReal

[1] 1.78 1.60 1.49 1.87 1.70 1.56 1.65

Se puede operar con vectores de tamaños diferentes, en este caso el vector más pequeño se replica

In [22]:
alturas*c(1,0)

Warning message in alturas * c(1, 0):
“longer object length is not a multiple of shorter object length”

[1] 1.80 0.00 1.50 0.00 1.75 0.00 1.65

Concatenar vectores

In [23]:
c(alturas,2,1.8,17)

[1]  1.80  1.60  1.50  1.90  1.75  1.63  1.65  2.00  1.80 17.00

In [24]:
length(alturas)
alturas[18]<-9

[1] 7

In [25]:
alturas

[1] 1.80 1.60 1.50 1.90 1.75 1.63 1.65   NA   NA   NA   NA   NA   NA   NA   NA
[16]   NA   NA 9.00

## Listas

Las listas se pueden considerar como vectores que pueden almacenar cualquier tipo de dato.

In [26]:
myList<-list(1,3,"catorce","panama")
str(myList)

List of 4
 $ : num 1
 $ : num 3
 $ : chr "catorce"
 $ : chr "panama"


Podemos asignar un nombre a cada valor

In [27]:
datosPersonales<-list(nombre="Philip",
                   apellido="García",
                   teléfono=600100100)
datosPersonales

$nombre
[1] "Philip"

$apellido
[1] "García"

$teléfono
[1] 600100100

### Acceso a elementos

Podemos acceder a los distintos elementos utilizando su índice o nombre:

In [28]:
datosPersonales[[1]]

[1] "Philip"

In [29]:
datosPersonales[["nombre"]]

[1] "Philip"

In [30]:
datosPersonales$nombre

[1] "Philip"

In [31]:
datosPersonales[["direccion"]]<-list(ciudad="Madrid",calle="Desengaño",numero=21)
datosPersonales[["direccion"]]

$ciudad
[1] "Madrid"

$calle
[1] "Desengaño"

$numero
[1] 21

In [32]:
print(paste("La longitud total de la lista es",length(datosPersonales)))

[1] "La longitud total de la lista es 4"


## Factores

Útiles cuando trabajamos con variables categóricas. Ej: Población de origen, colores, sabores

In [33]:
saboresDePlatos<-c("Dulce","Salado","Ácido","Amargo","Umami","Dulce","Salado","Ácido","Umami","Umami","Salado")
saboresDePlatosFactor<-factor(saboresDePlatos)

summary(saboresDePlatos)
summary(saboresDePlatosFactor)

   Length     Class      Mode 
       11 character character 

Ácido Amargo  Dulce Salado  Umami 
     2      1      2      3      3

In [34]:
print("Los factores internamente se gestionan como enteros")
as.numeric(saboresDePlatosFactor)

[1] "Los factores internamente se gestionan como enteros"


[1] 3 4 1 2 5 3 4 1 5 5 4

In [35]:
print(paste("Podemos ver los niveles con el comando levels:",
            paste(levels(saboresDePlatosFactor),collapse=",")))

[1] "Podemos ver los niveles con el comando levels: Ácido,Amargo,Dulce,Salado,Umami"


In [36]:
factor(c(1,0,0,1,0,1),labels=c("NO","SI"))

[1] SI NO NO SI NO SI
Levels: NO SI

In [37]:
factor(c(10,5,5,0,5,0),labels=c("BAJO","MEDIO","ALTO"))

[1] ALTO  MEDIO MEDIO BAJO  MEDIO BAJO 
Levels: BAJO MEDIO ALTO

# Matrices

Podemos crear matrices con la función matrix. Como parámetros de entrada recibe un vector y el número de columnas (*ncol*) o filas (nrow). Un parámetro opcional (*byrow*) indica si la matriz se va a rellenar por filas o por columnas (valor por defecto)

In [38]:
m1<-matrix(c(1:12),ncol=3)
m1

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [39]:
m2<-matrix(c(1:12),ncol=3,byrow=T)
m2

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

La dimensión del array se puede ver con la función *dim()* o con *str()*

In [40]:
dim(m1)

[1] 4 3

In [41]:
str(m1)

 int [1:4, 1:3] 1 2 3 4 5 6 7 8 9 10 ...


### Acceso

El acceso se realiza igual que los vectores, pero aquí tenemos dos dimensiones.

In [42]:
m1[1,3]

[1] 9

También podemos dar nombres a las filas y columnas para luego poder acceder utilizando el nombre

In [43]:
colnames(m1)<-paste0("col",1:3)
rownames(m1)<-paste0("row",1:4)
m1
paste("El valor de 'row1' y 'col1' es:",m1["row1","col3"])

col1 col2 col3
row1 1    5     9  
row2 2    6    10  
row3 3    7    11  
row4 4    8    12

[1] "El valor de 'row1' y 'col1' es: 9"

Las funciones *colnames* y *rownames* 

In [44]:
colnames(m1)

[1] "col1" "col2" "col3"

### Operaciones con matrices 
#### Álgebra lineal básica

Transpuesta

In [45]:
t(m1)

row1 row2 row3 row4
col1 1     2    3    4  
col2 5     6    7    8  
col3 9    10   11   12

Suma de constante

In [46]:
m1+10

col1 col2 col3
row1 11   15   19  
row2 12   16   20  
row3 13   17   21  
row4 14   18   22

Suma de matrices

In [47]:
m1+m2

col1 col2 col3
row1  2    7   12  
row2  6   11   16  
row3 10   15   20  
row4 14   19   24

Multiplicación de matrices

In [48]:
m1 %*% matrix(rep(1,12),nrow=3)

[,1] [,2] [,3] [,4]
row1 15   15   15   15  
row2 18   18   18   18  
row3 21   21   21   21  
row4 24   24   24   24

# Tablas

Se utilizan para estudios de frecuencia. Cuentan el número de veces que ha ocurrido algo.

In [49]:
tblSabores<-table(saboresDePlatos)
tblSabores

saboresDePlatos
 Ácido Amargo  Dulce Salado  Umami 
     2      1      2      3      3 

In [50]:
names(tblSabores)

[1] "Ácido"  "Amargo" "Dulce"  "Salado" "Umami"

In [51]:
str(tblSabores)

 'table' int [1:5(1d)] 2 1 2 3 3
 - attr(*, "dimnames")=List of 1
  ..$ saboresDePlatos: chr [1:5] "Ácido" "Amargo" "Dulce" "Salado" ...


Los atributos son una lista de propiedades asociadas a un objeto en R

In [52]:
attributes(tblSabores)

$dim
[1] 5

$dimnames
$dimnames$saboresDePlatos
[1] "Ácido"  "Amargo" "Dulce"  "Salado" "Umami" 


$class
[1] "table"

In [53]:
color  <- c("marrón","negro","blanco","negro","blanco","negro","negro","marrón","marrón","marrón")
animal <- c("gato","gato","perro","gato","gato","perro","perro","perro","gato","gato")

table(animal,color)

       color
animal  blanco marrón negro
  gato       1      3     2
  perro      1      1     2

## Data Frame

Conjunto de vectores de la misma longitud. Cada vector puede ser de un tipo diferente.

In [54]:
plt <- c("Bollo","Palomitas","Limón","Ginebra","Noodles","Caramelo","Patatas fritas","Naranja","Ternera","Cerdo","Sopa")
cal <-c(150,200,10,20,200,5,500,15,450,460,30)

comidas<-data.frame(plato=plt, calorias=cal, sabor=saboresDePlatosFactor, stringsAsFactors = F)
comidas
str(comidas)

plato          calorias sabor 
1  Bollo          150      Dulce 
2  Palomitas      200      Salado
3  Limón           10      Ácido 
4  Ginebra         20      Amargo
5  Noodles        200      Umami 
6  Caramelo         5      Dulce 
7  Patatas fritas 500      Salado
8  Naranja         15      Ácido 
9  Ternera        450      Umami 
10 Cerdo          460      Umami 
11 Sopa            30      Salado

'data.frame':	11 obs. of  3 variables:
 $ plato   : chr  "Bollo" "Palomitas" "Limón" "Ginebra" ...
 $ calorias: num  150 200 10 20 200 5 500 15 450 460 ...
 $ sabor   : Factor w/ 5 levels "Ácido","Amargo",..: 3 4 1 2 5 3 4 1 5 5 ...


### Acceso a elementos de un data frame

Acceso por filas:

In [55]:
comidas[2:3,]

plato     calorias sabor 
2 Palomitas 200      Salado
3 Limón      10      Ácido

Acceso por columnas:

In [56]:
comidas[,c("plato","calorias")]

plato          calorias
1  Bollo          150     
2  Palomitas      200     
3  Limón           10     
4  Ginebra         20     
5  Noodles        200     
6  Caramelo         5     
7  Patatas fritas 500     
8  Naranja         15     
9  Ternera        450     
10 Cerdo          460     
11 Sopa            30

Se puede usar el símbolo **$** para acceder a una columna.  
Las siguientes dos llamadas son equivalentes:

In [57]:
comidas$plato[2:3]
comidas[2:3,"plato"]

[1] "Palomitas" "Limón"

[1] "Palomitas" "Limón"

También podemos dar nombres a las filas

In [58]:
rownames(comidas)<-paste0("comida",1:nrow(comidas))
comidas

plato          calorias sabor 
comida1  Bollo          150      Dulce 
comida2  Palomitas      200      Salado
comida3  Limón           10      Ácido 
comida4  Ginebra         20      Amargo
comida5  Noodles        200      Umami 
comida6  Caramelo         5      Dulce 
comida7  Patatas fritas 500      Salado
comida8  Naranja         15      Ácido 
comida9  Ternera        450      Umami 
comida10 Cerdo          460      Umami 
comida11 Sopa            30      Salado

In [59]:
comidas["comida5","calorias"]

[1] 200

El nombre de las columnas y de las filas se puede obtener y modificar con las funciones **colnames()** y **rownames()**.

In [60]:
colnames(comidas)
rownames(comidas)

[1] "plato"    "calorias" "sabor"

[1] "comida1"  "comida2"  "comida3"  "comida4"  "comida5"  "comida6" 
 [7] "comida7"  "comida8"  "comida9"  "comida10" "comida11"